services:
  db:
    image: postgres:17-alpine
    container_name: kps-postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db_manage_keuangan

    ports:
      - "5432:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    container_name: kps-backend

    build:
      context: .
      dockerfile: Dockerfile.dev

    ports:
      - "3000:3000"

    env_file:
      - .env

    environment:
      DATABASE_URL: postgresql://postgres:admin@db:5432/db_manage_keuangan

    volumes:
      - .:/app
      - /app/node_modules

    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata: